---
# tasks file for conda

  - name: Load variable files
    include_vars:
      dir: "{{ role_path }}/vars"
      extensions: [yml]


  - name: Check for installation of anaconda
    stat:
      path: "{{ anaconda_install_dir }}/bin/conda"
    register: anaconda_bin_conda


  - when: not anaconda_bin_conda.stat.exists
    block:
    - name: Download anaconda installer
      get_url:
        url: "https://repo.anaconda.com/archive/{{ anaconda_installer_sh }}"
        dest: "/tmp/{{ anaconda_installer_sh }}"
        mode: 0755

    - name: Run the installer
      shell: "bash /tmp/{{ anaconda_installer_sh }} -f -b -p {{ anaconda_install_dir }}"

    - name: Make conda as system default python
      copy:
        dest: /etc/profile.d/conda.sh
        content: "PATH={{ anaconda_install_dir }}/bin:$PATH"

    always:
    - name: Delete anaconda installer ...
      file:
        path: "/tmp/{{ anaconda_installer_sh }}"
        state: absent


  - name: Update conda packages ...
    when: anaconda_pkg_update
    command: "{{ item }}"
    with_items:
      - "{{ anaconda_install_dir }}/bin/conda update -y conda"
      - "{{ anaconda_install_dir }}/bin/conda update -y --all"

